name: android_build

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
      # 拉取 android_builder 的源代码
        uses: actions/checkout@v2
      - name: Set up JDK
      # 设置 Java 运行环境
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          # 用 1.8 版本覆盖环境中自带的 Java 11 版本
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install 
      - name: Build
        run: |
          npm install -g cordova
          cordova platform add android
          cordova build android
          cd platforms/android/app/build/outputs/apk
          ls
        
        
